name: on_in_bus
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  cloud_firestore: ^3.4.3
  cloud_firestore_odm: ^1.0.0-dev.25
  currency_text_input_formatter: ^2.1.7
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.10
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  cloud_firestore_odm_generator: ^1.0.0-dev.25
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
